# Generated by Django 5.2.1 on 2025-05-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="quote_currency",
            field=models.CharField(default="USD", max_length=50),
        ),
    ]
