# Generated by Django 5.2.1 on 2025-06-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_trades", "0001_initial"),
        ("trading", "0002_alter_market_quote_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagesubscription",
            name="is_auto_trading_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="packagesubscription",
            name="last_trade_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagesubscription",
            name="total_profit_earned",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name="tradingpackage",
            name="features",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradingpackage",
            name="max_trade_amount_percentage",
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="tradingpackage",
            name="max_trades_per_day",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="tradingpackage",
            name="min_trade_amount_percentage",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="tradingpackage",
            name="preferred_markets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Preferred markets for auto-trading. If empty, uses all active markets",
                to="trading.market",
            ),
        ),
        migrations.AddField(
            model_name="tradingpackage",
            name="risk_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tradingpackage",
            name="trade_frequency_hours",
            field=models.IntegerField(
                default=4, help_text="Minimum hours between trades"
            ),
        ),
        migrations.CreateModel(
            name="AutoTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_trades",
                        to="auto_trades.packagesubscription",
                    ),
                ),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_trade_info",
                        to="trading.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
