# Generated by Django 5.2.1 on 2025-05-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptowallet",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="fee",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="tx_hash",
        ),
    ]
