# Generated by Django 5.2.1 on 2025-05-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_remove_cryptowallet_private_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotype",
            name="coingecko_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
