# Generated by Django 5.2.1 on 2025-05-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_cryptotype_coingecko_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptotype",
            name="symbol",
            field=models.CharField(max_length=50),
        ),
    ]
