# Generated by Django 5.2.1 on 2025-06-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_alter_cryptotype_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotype",
            name="coinpaprika_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
