# Generated by Django 5.2.1 on 2025-06-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_cryptotype_coinpaprika_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotype",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
