# Generated by Django 5.2.1 on 2025-06-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0006_cryptotype_logo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptowallet",
            name="wallet_address",
            field=models.CharField(max_length=100),
        ),
    ]
