# Generated by Django 5.2.1 on 2025-06-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0007_alter_cryptowallet_wallet_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="conversion_rate",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=24, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="usd_amount",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("conversion", "Conversion"),
                ],
                max_length=15,
            ),
        ),
    ]
