# Generated by Django 5.2.1 on 2025-05-27 22:00

import apps.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.authentication.models.CustomUserManager()),
            ],
        ),
    ]
